### ISSUE TITLE
Initial & continuous setup for repo

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo-cli#2]
## To-do

[Readme badges](https://github.com/code-collabo/node-mongo-cli/issues/2#issuecomment-802731978) 👈🏽

[For later](https://github.com/code-collabo/node-mongo-cli/issues/2#issuecomment-798398880) 👈🏽

**Main tasks (main repo)**

**Set up environment (Config):**
- [x] Initialize git repo with .gitignore file.
- [x] Create licence file.
- [x] Create readme file.
- [x] Set up CI for node.
- [x] Add package.json, install dependencies & npm link.
- [x] configure .eslintrc.json (after installing dependency).
- [x] Add .editorconfig.

***Reduce text in readme*** 👇🏽

**Create issues that contain:**
- [x] Project details & first task #1 
- [x] Contribution & community guidelines & add content code-collabo/node-mongo-docs#3 
- [x] Project resources code-collabo/node-mongo-docs#1
- [x] Add the above links in the [readme](https://github.com/code-collabo/node-mongo-cli).

- [x] Link it to issues & assignment in code-collabo/node-mongo-docs#3

These contents will also be included in documentation later on.

**Other contents/sections to add to readme:**
- [x] Git workflow.
- [x] Technologies (icons).
- [x] How to contribute to the project (header, brief content to go along with the already existing 3 links).

**GitHub project:**
- [x] Automate github projects (issues, pull requests etc)
- [x] Add testing checklist (template) for (incoming) pull requests.

**Manage branch protection rule:**
- [ ] node-mongo-cli repo
- [ ] node-mongo-starter-kit repo
- [ ] node-mongo-kit-commonjs repo

**Add before publishing 1st release:**
- [x] Update brief intro + description (CLI readme).
- [x] Add how to use section (CLI readme).

**Doc**
- [x] Production-ready documentation: Decide on what tool, site or platform to use to write documentation.

#5 #19

**Comment by Ifycode** [comment]
Store these next tasks here:

Create separate repo for documentation.
Move all issues with label "documentation" to documentation repo.

Create separate issue for storing resources used for the project - also in the documentation repo.

**Comment by Ifycode** [comment]
**Add the following issue(s) later:**
- [ ] Add badges to readme of both CLI & starter repos to show number of downloads, stars, forks, contributors etc.

**Save these here for subsequent issues you will write:*
* For every cli-related code/issue, make another issue for testing with jasmine - in this test issue, reference the related CLI issue & specify that whoever will work on the test should work together with the person who is taking on the cli issue.

**Comment by Ifycode** [comment]
#### CLI
[![HitCount](http://hits.dwyl.com/code-collabo/node-mongo-cli.svg)](http://hits.dwyl.com/code-collabo/node-mongo-cli)

**Comment by Ifycode** [comment]
@all-contributors please add @Ifycode for admin, CI and code

**Comment by Ifycode** [comment]
@all-contributors please add @IsraelObiagba for mentoring

**Comment by Ifycode** [comment]
@all-contributors please add @jiobiagba for mentoring

**Comment by Ifycode** [comment]
@all-contributors please add @Ifycode for code, maintenance, ideas

**Comment by Ifycode** [comment]
@all-contributors please add @Ifycode for code, doc

**Comment by Ifycode** [comment]
@all-contributors please add @all-contributors for infra
