### ISSUE TITLE
Starter kit issues (collection)

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo-cli#23]
***Click on the link beside any item below to read detailed description of that particular issue:***
- [ ] Add CORS to both starter-kit and starter-cjs repos #27 
- [ ] Add files/folder structure & description to starter-kit readme and starter-cjs readme #26 
- [ ] Starter kit usage & installation guide test #28
- [x] Convert package.json in the starter-cjs to common js #41 
- [x] Change import & export syntax to common js syntax in starter-cjs #42
