### ISSUE TITLE
CLI issues (collection)

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo-cli#32]
***Click on the link beside any item below to read detailed description of that particular issue:***
- [x] Customize & add base code for CLI project to officially begin #30
- [x] Fix syntax/import error in jasmine, babel, node #33 
- [x] Add prompt for options.folderName in cli.js #36
- [x] Add prompt for options.template in cli.js #43 
- [x] Customize cli on (pre) install #49
