### ISSUE TITLE
Change import & export syntax to commonjs require syntax in starter-cjs

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo-cli#42]
node-mongo-starter-cjs has been created from node-mongo-starter-kit i.e. the repo was imported from & therefore is the exact copy of the node-mongo-starter-kit. 

The starter-kit uses Babel to transpile our code so that we are able to use the `import` & `export` syntax of importing and exporting modules. The starter-cjs on the other hand needs to use the commonjs `require` syntax. 

## Task
Change import & export syntax to commonjs require syntax in all files affected in the [starter-cjs](https://github.com/code-collabo/node-mongo-starter-cjs) .

📌 **Please use** `const` **keyword e.g. `const express = require('express');`, not** `var` e.g. 

- [x] srcServer/startMessage.js
- [x] srcServer/server.js
- [x] srcServer/app.js
- [x] srcServer/db.js
- [x] srcServer/atlas/db.js
- [x] srcServer/api/controllers/appController.js
- [x] srcServer/api/controllers/starterController.js
- [x] srcServer/api/models/starter.js

#23
