### ISSUE TITLE
Ensure code consistency, customize and fix causes of confusion

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo-cli#98]
#### Task description
Ensure code consistency, customize and fix causes of confusion. Fix or change the following:
- [x] Ensure project uses arrow functions throughout 
- [x] Change function names where necessary
- [x] Change `cliOptions` to `options` variable or parameter
- [x] Improve error or console messages where needed to prevent confusion 
- [x] Any other thing related to consistency and preventing confusion
